// Bakes the agent pod's files into the bundle as seed.generated.ts.
//
// The pod is made from nothing by the extension when it loads - a ConfigMap of these files and
// a Deployment running stock node over them - so the files have to travel with the bundle.
// Real files under pkg/agents/seed rather than strings built here, so they are linted and read
// like the scripts they are. Run after editing anything there:
//   node scripts/gen-seed.mjs
// The output is committed, so normal builds never run this.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SEED = path.join(here, '..', 'pkg', 'agents', 'seed');
const OUT = path.join(here, '..', 'pkg', 'agents', 'seed.generated.ts');

// shell.sh un-flattens skill directories with the separator Extension Studio's pods use; this
// pod carries no skills but the script is the same script, so the token is filled the same way.
const SUBSTITUTIONS = { __PATH_SEPARATOR__: '__' };

function podFile(file) {
  let contents = fs.readFileSync(file, 'utf8');

  for (const [token, value] of Object.entries(SUBSTITUTIONS)) {
    contents = contents.split(token).join(value);
  }

  const leftover = contents.match(/__[A-Z_]+__/);

  if (leftover) {
    throw new Error(`${ path.basename(file) } still has an unsubstituted token: ${ leftover[0] }`);
  }

  return contents;
}

// The shared terminal scripts first, then the agent's own on top: a name in both is the
// agent's, which is how it gets its own boot script and CLAUDE.md.
const files = {};

for (const name of fs.readdirSync(SEED)) {
  const full = path.join(SEED, name);

  if (fs.statSync(full).isFile()) {
    files[name] = podFile(full);
  }
}

for (const name of fs.readdirSync(path.join(SEED, 'agent'))) {
  files[name] = podFile(path.join(SEED, 'agent', name));
}

const body = Object.keys(files).sort().map((name) => `  ${ JSON.stringify(name) }: ${ JSON.stringify(files[name]) },`).join('\n');

fs.writeFileSync(OUT, `/* eslint-disable */
// Generated by scripts/gen-seed.mjs from pkg/agents/seed. Do not edit.
export const AGENT_FILES: Record<string, string> = {
${ body }
};
`);

const size = Object.values(files).reduce((total, text) => total + Buffer.byteLength(text), 0);

console.log(`agent seed: ${ Object.keys(files).length } files, ${ (size / 1024).toFixed(1) } KiB -> ${ path.relative(process.cwd(), OUT) }`);
